name: Build Node.js for Android (ARM64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Node.js source (shallow)
        uses: actions/checkout@v5
        with:
          repository: nodejs/node
          ref: main
          fetch-depth: 1

      - name: Install build dependencies
        run: |
          sudo apt update -qq
          sudo apt install -y -qq python3 make clang curl pkg-config xz-utils unzip aria2

      - name: Cache Android NDK r29
        id: cache-ndk
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/android-ndk-r29
          key: ndk-r29

      - name: Download and setup Android NDK r29
        if: steps.cache-ndk.outputs.cache-hit != 'true'
        run: |
          cd ${{ runner.temp }}
          echo "Downloading Android NDK r29..."
          aria2c -x 16 -s 16 -q https://dl.google.com/android/repository/android-ndk-r29-linux.zip -o android-ndk-r29.zip
          unzip -q android-ndk-r29.zip
          echo "NDK extracted."

      - name: Set NDK environment variables
        run: |
          echo "ANDROID_NDK_HOME=${{ runner.temp }}/android-ndk-r29" >> $GITHUB_ENV
          echo "${{ runner.temp }}/android-ndk-r29" >> $GITHUB_PATH

      - name: Verify NDK setup
        run: |
          echo "Using NDK at: $ANDROID_NDK_HOME"
          $ANDROID_NDK_HOME/ndk-build --version || echo "NDK ready"

      - name: Configure Node.js for Android ARM64
        run: |
          echo "Running android-configure..."
          ./android-configure $ANDROID_NDK_HOME 30 arm64

      - name: Build Node.js (official command)
        run: |
          echo "Building Node.js with make -j4..."
          make -j4
          echo "Build complete."

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          cp out/Release/libnode.so artifacts/ || echo "libnode.so missing!"
          cp out/Release/node artifacts/ || echo "node binary missing!"
          ls -lh artifacts

      - name: Upload build artifacts
        uses: actions/upload-artifact@v5
        with:
          name: node-android-arm64
          path: artifacts/
