name: Build Python for Android

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.14'
  BUILDOZER_VERSION: 'stable'

jobs:
  build-android:
    name: Build Android APK/AAB
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        arch: [armeabi-v7a, arm64-v8a]
        build-type: [debug, release]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          path: master

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: x64

      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: .buildozer_global
          key: buildozer-global-${{ runner.os }}-${{ hashFiles('**/buildozer.spec') }}
          restore-keys: |
            buildozer-global-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade Cython==3.1.6
          pip install --upgrade setuptools wheel

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        env:
          APP_ANDROID_ARCH: ${{ matrix.arch }}
        with:
          repository_root: master
          workdir: .
          buildozer_version: ${{ env.BUILDOZER_VERSION }}
          command: buildozer android ${{ matrix.build-type }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: python-android-${{ matrix.arch }}-${{ matrix.build-type }}
          path: ${{ steps.buildozer.outputs.filename }}
          retention-days: 30

      - name: Upload to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.buildozer.outputs.filename }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
