name: Build Node.js for Android (ARM64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Node.js source (shallow)
        uses: actions/checkout@v5
        with:
          repository: nodejs/node
          ref: main
          fetch-depth: 1

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install -y python3 make clang curl pkg-config xz-utils unzip

      - name: Download and setup Android NDK r29
        run: |
          cd $HOME
          wget https://dl.google.com/android/repository/android-ndk-r29-linux.zip
          unzip -q android-ndk-r29-linux.zip
          echo "ANDROID_NDK_HOME=$HOME/android-ndk-r29" >> $GITHUB_ENV
          echo "$HOME/android-ndk-r29" >> $GITHUB_PATH

      - name: Verify NDK installation
        run: |
          echo "NDK path: $ANDROID_NDK_HOME"
          ls -lh $ANDROID_NDK_HOME
          $ANDROID_NDK_HOME/ndk-build --version || echo "NDK ready"

      - name: Configure Node.js for Android ARM64
        run: |
          ./android-configure $ANDROID_NDK_HOME 36 arm64

      - name: Build Node.js
        run: |
          make -j$(nproc)

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          cp out/Release/libnode.so artifacts/ || echo "libnode.so missing!"
          cp out/Release/node artifacts/ || echo "node binary missing!"
          ls -lh artifacts

      - name: Upload build artifacts
        uses: actions/upload-artifact@v5
        with:
          name: node-android-arm64
          path: artifacts/
