name: Build Bun for Termux (Android ARM64)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup build dependencies
        run: |
          sudo apt update -y
          sudo apt install -y \
            clang llvm cmake make git ninja-build \
            curl pkg-config python3 libtool autoconf \
            automake ccache rustc cargo golang ruby-full xz-utils

      - name: Install Zig (latest)
        run: |
          ZIG_VERSION="0.15.2"
          curl -LO "https://ziglang.org/download/0.15.2/zig-x86_64-linux-0.15.2.tar.xz"
          tar -xf "zig-linux-x86_64-0.15.2.tar.xz"
          sudo mv "zig-linux-x86_64-0.15.2" /usr/local/zig
          sudo ln -s /usr/local/zig/zig /usr/local/bin/zig
          zig version

      - name: Environment setup
        run: |
          export CC=clang
          export CXX=clang++
          export CFLAGS="-fPIC -O3 -fno-strict-aliasing"
          export LDFLAGS="-static-libstdc++"
          export BUN_DEPS_NO_SANDBOX=1
          export ZIG_GLOBAL_CACHE_DIR=$HOME/.cache/zig
          mkdir -p build

      - name: Build Bun for Termux (Android ARM64)
        run: |
          zig build -Dtarget=aarch64-linux-android \
                    -Doptimize=ReleaseFast \
                    -DBUN_NO_SANDBOX=1 \
                    -DUSE_STATIC_LIBATOMIC=OFF
        env:
          CC: clang
          CXX: clang++

      - name: Move and compress binary
        run: |
          mkdir -p dist
          cp zig-out/bin/bun dist/bun-termux
          strip dist/bun-termux || true
          tar -czf bun-termux-aarch64.tar.gz -C dist bun-termux

      - name: Upload Bun Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bun-termux-aarch64
          path: bun-termux-aarch64.tar.gz

      - name: Display success info
        run: |
          echo "✅ Bun for Termux (aarch64) built successfully!"
          echo "Artifact: bun-termux-aarch64.tar.gz"
